;;; flycheck-plantuml-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flycheck-plantuml.el

(autoload 'flycheck-plantuml-setup "flycheck-plantuml" "\
Setup flycheck-plantuml.

Add `plantuml' to `flycheck-checkers'." t)

;;; End of scraped data

(provide 'flycheck-plantuml-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-plantuml-autoloads.el ends here
